### ISSUE TITLE
what was the result

### ISSUE THREAD

**Issue by xiaozhuo12138** [s110065524/Utilizing-speech-Self-supervised-Representations-for-Singing-Quality-Evaluation#1]

**Comment by s110065524** [comment]
hello, here is my research result, welcome to cite this paper
https://dl.acm.org/doi/abs/10.1145/3595916.3626443
while I didn't upload latest code to this repo
If you have any questions, feel free to ask me

**Comment by xiaozhuo12138** [comment]
How much training data do I need? I used 1000 songs and about 10000 segments, which makes it easy to overfit

**Comment by s110065524** [comment]
I use the DAMP dataset from the author of the original paper, you can contact her and she will send you the dataset.

**Comment by xiaozhuo12138** [comment]
Thank you for your answer
